spring:
  application:
    name: xiaohai-home
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
#    openai:
#      api-key: ${DASHSCOPE_API_KEY}
#      base-url: https://dashscope.aliyuncs.com/compatible-mode
#    deepseek:
#      api-key: ${DASHSCOPE_API_KEY}
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
#      chat:
#        options:
#          model: deepseek-r1
#          temperature: 0.7
    alibaba:
      toolcalling:
        baidu:
          search:
            enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      # 应用健康状态检查，携带详细新学年
      show-details: always
  tracing:
    sampling:
      # trace 采样信息，记录每个请求
      probability: 1.0
server:
  port: 8089