spring:
  application:
    name: xiaohai-home
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
#    openai:
#      api-key: ${DASHSCOPE_API_KEY}
#      base-url: https://dashscope.aliyuncs.com/compatible-mode
#    deepseek:
#      api-key: ${DASHSCOPE_API_KEY}
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
#      chat:
#        options:
#          model: deepseek-r1
#          temperature: 0.7

server:
  port: 8089