spring:
  application:
    name: xiaohai-home
  ai:
    chat:
      client:
        observations:
          # default value is false.
          log-prompt: true
      observations:
        log-prompt: true
        log-completion: true
        include-error-logging: true
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
    mcp:
      server:
        name: xiaohai-home-weather-mcp
        version: 1.0.0
        type: SYNC
        sse-message-endpoint: /mcp/messages
        stdio: false
        sse-endpoint: /sse
    #    openai:
#      api-key: ${DASHSCOPE_API_KEY}
#      base-url: https://dashscope.aliyuncs.com/compatible-mode
#    deepseek:
#      api-key: ${DASHSCOPE_API_KEY}
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
#      chat:
#        options:
#          model: deepseek-r1
#          temperature: 0.7
    alibaba:
      toolcalling:
        baidu:
          search:
            enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      # 应用健康状态检查，携带详细新学年
      show-details: always
  tracing:
    sampling:
      # trace 采样信息，记录每个请求
      probability: 1.0
server:
  port: 8080

otel:
  traces:
    exporter: otlp
    sampler: always_on
  metrics:
    exporter: otlp
  # logs exportation inhibited for langfuse currently cannot support
  logs:
    exporter: none
  exporter:
    otlp:
      endpoint: "https://cloud.langfuse.com/api/public/otel"
      headers:
        Authorization: "Basic ***"
      protocol: http/protobuf

logging:
  level:
    io.opentelemetry: DEBUG
    org.springframework.ai: DEBUG